package exception;

public class Test13 {
	public static void main(String args[])
	{
	    try
		{
			
		}
	    finally
	    {
	    	
	    }
	    try
	    {
	    	
	    }
	    catch(ArithmeticException e)
	    {
	    	
	    }
	}

}
