package exception;

public class Test14 {
	public static void main(String args[])
	{
		try
		{
			try
			{
				
			}
			catch (Exception e)
			{
				
			}
		}
		catch(ArithmeticException e)
		{
			
		}
	}

}
